### ISSUE TITLE
Non-standard fields from Azure AD

### ISSUE THREAD

**Issue by jlowe64** [Microsoft/moodle-local_o365#13]
Is there any plans to put non-standard field support from Azure AD? The LDAP plugin has the ability to sync fields that are custom fields created in AD.

It seems to be a fixed array in this plugin, without any ability to be dynamic. 

An example would be if a field called "StudentID" were added to Azure AD, being able to sync this field back to Moodle would be very beneficial for reporting purposes.

**Comment by chadcarlton** [comment]
I put a similar question over in 
https://github.com/Microsoft/o365-moodle/issues/210

**Comment by nimojg-microsoft** [comment]
Closing as this issue was posted in the https://github.com/microsoft/o365-moodle/issues page where we are tracking them.
