### ISSUE TITLE
Type text/x-c is not supported. Please upload a plain-text CSV.

### ISSUE THREAD

**Issue by leonhedding** [Microsoft/moodle-local_o365#3]
I have been using the merge tool to quickly connect our Moodle database with our Azure AD user accounts. I have been able to import 1000's of users. But am getting this error with one entry.

`Type text/x-c is not supported. Please upload a plain-text CSV.`

I have tracked it down to content of the file. To reproduce the problem you created a csv file with the following content:

`charlie,charlie.smith@example.onmicrosoft.com`

Then upload the file and it complains the above error.

It seems that any time "charlie" is mentioned in the moodle user column I get the above error. I think the checking for this is done in classes/page/acp.php.

**Comment by rlcharles** [comment]
After some invesitgation it may relate to a bug in PHP ? What version of php are you using now and does it still occur ?

**Comment by leonhedding** [comment]
PHP 5.5. I have not tried since February.

**Comment by rlcharles** [comment]
Some versions of php 5.5 have reported file types being detected incorrectly. Upgrading to a newer version of PHP should fix this issue.
https://bugs.php.net/bug.php?id=53035

**Comment by jamesmcq** [comment]
@leonhedding Hi Leon - going to close this as we haven't heard anything in a while. If you are still experiencing this problem, please create a new issue in https://github.com/Microsoft/o365-moodle
