### ISSUE TITLE
Users are not removed from Moodle when synchronising with Azure AD

### ISSUE THREAD

**Issue by nova2k** [Microsoft/moodle-local_o365#5]
Hi,

I'm using Moodle 3.0.2 and Microsoft Office 365 Integration plugin with latest updates.

When I add new users to Azure AD, those accounts have no issue synchronizing with Moodle.

However, when I delete users from Azure AD, those accounts are not removed from Moodle.

Anyone has the same issue or has ideas how to fix it?

Cheers,

**Comment by rlcharles** [comment]
On the options tab in Site administration / ► Plugins / ► Local plugins / ► Microsoft Office 365 Integration there is a checkbox "Delete previously synced accounts in Moodle when they are deleted from Azure AD", is this checked ?

**Comment by jamesmcq** [comment]
Hi @nova2k - Closing this issue since we haven't heard anything in a while. If you are still experiencing this problem, please create a new issue in https://github.com/Microsoft/o365-moodle. Thanks!
