### ISSUE TITLE
Parse error: syntax error, unexpected '*', expecting ')' inlocal/o365/classes/rest/sharepoint.php on line 983

### ISSUE THREAD

**Issue by jeyaprakashk** [Microsoft/moodle-local_o365#7]
Parse error: syntax error, unexpected '*', expecting ')' in local/o365/classes/rest/sharepoint.php on line 983

**Comment by jeyaprakashk** [comment]
Can we make the following change on line 193:
`public function upload_video($channelid, $videoid, $filename, $offsetsize = 8388608 ) {`
instead of 
`public function upload_video($channelid, $videoid, $filename, $offsetsize = 8192 * 1024) {`

**Comment by number33** [comment]
Thanks for the report. We currently have a fix for this, see branches wip-MSFTMPP-530-mXX
