### ISSUE TITLE
forum topic creation fails

### ISSUE THREAD

**Issue by leonhedding** [Microsoft/moodle-local_o365#8]
When I attempt to create a forum topic I get this error.

> Parse error: syntax error, unexpected '*', expecting ')' in /var/www/moodle/html/local/o365/classes/rest/sharepoint.php on line 983

This was fixed by putting quotes around '8192 * 1024' on the line.

**Comment by rlcharles** [comment]
Changing 8192 * 1024 to 8388608 will be the correct solution. The full fix is at.
https://github.com/Microsoft/o365-moodle/commit/4a4b3ce3af8dca2983fa9eb1cc0439124ab14ba1
